### ISSUE TITLE
Stuck on GRPC (ChannelCredentials::createInsecure();)

### ISSUE THREAD

**Issue by tslater** [pixelfederation/vitess-php-pdo#1]
I tried to follow all the instructions to install GRCP and VitessPdoPDO. PHP suddenly dies on this line in _Vitess.php_: `$credentials      = ChannelCredentials::createInsecure();`
I know this doesn't directly relate to VitessPdoPDO. I really just need to get Vitess/GRCP going in general. I'm just not sure what else to do. I don't get any error messages or anything.

**Comment by Rastusik** [comment]
you need to install the grpc extension (v0.7-beta) from here: https://pecl.php.net/package/gRPC

**Comment by tslater** [comment]
I installed 0.6.1 because the README says "On OS X there is a problem with the current GRPC version (0.12) and PHP GRPC extension (0.7). GRPC 0.11 and PHP GRPC 0.61 worked fine." Should I only use v0.7?

**Comment by enisoc** [comment]
The README on this repo is a little out of sync with the main vitess repo at the moment. Recently we (main Vitess) switched to gRPC 0.12, and as part of that we had to update to requiring 0.7+ for the PHP gRPC plugin.

**Comment by Rastusik** [comment]
Yes, I apologise, the README is misleading - it doesn't mean that the PDO driver doesn't work with the mentioned versions, only that it works a little bit slower. Although I was testing it yesterday with a different Vitess setup and I think the problem wasn't there anymore.

The driver and README aren't out of sync with the Vitess repo, only the text is misleading.

@tslater yes, you need to use the 0.7 version

**Comment by tslater** [comment]
Cool. I couldn't find a binary for gRPC 0.12 (for Ubuntu/Debian). I'm currently building myself, which results in a pretty big docker image. Either of you know of a binary for that?

**Comment by Rastusik** [comment]
I used this https://github.com/grpc/grpc/tree/master/src/php#quick-install
