### ISSUE TITLE
PDO::lastResult not set on inserts

### ISSUE THREAD

**Issue by wluo** [pixelfederation/vitess-php-pdo#10]
If i execute an insert like:

`getPdo()->prepare($query)->execute($bindings);`

then the PDO instance's `exec()` method is never called, which means `PDO::lastResult` is never set, which means you won't be able to retrieve the id of the newly inserted row.

The above is how Laravel/Eloquent implements its `insertGetId()` method. I see that the insert query is eventually executed by PDOStatement which does store the last result, including the last inserted id, but that result isn't propagated to the parent PDO instance.

**Comment by Rastusik** [comment]
fixed with 97f0d9d

**Comment by wluo** [comment]
Thanks for the quick fix Martin! I'll try it out with our test case.

**Comment by wluo** [comment]
The fix passes all our tests. Thanks again!
