### ISSUE TITLE
Update statement throws an exception

### ISSUE THREAD

**Issue by ghost** [pixelfederation/vitess-php-pdo#13]
Hi @Rastusik,

Is this code correct?
https://github.com/pixelfederation/vitess-php-pdo/blob/master/src/VitessPdo/PDO/Vitess/Vitess.php#L200
I'm trying to update a row without using of transaction. I've done it somewhere else but when I try it now it actually executes the query and after that throws an exception.

**Comment by Rastusik** [comment]
Hi @mohammad7293 , the code is correct, the point is that Vitess only supports writes in a transaction, so if there is no transaction active, it is being created and committed after the write query. What's the exception message?

**Comment by ghost** [comment]
In somewhere in my code im trying to update a record without starting a transaction. In the line that i have mentioned, the update query occurs but although the getTransaction() method returns an VTGateX object, the isInTransactionValue is false, so your code tries to run the commitTransaction method and it fails because you haven't start any transaction in this case. If i beginTransaction in mycode, i can't commit because you commited the transaction in your code before.

**Comment by ghost** [comment]
@Rastusik

**Comment by Rastusik** [comment]
that code is correct, maybe I didn't explain it clearly enough. It's exactly for your use case - write query without a transaction in the app context. There is also a unit test for this scenario. I'm 100% sure that it works in the PDO level. The getTransaction() always returns an object, because the transaction is created if it doesn't exist. I admit, the code isn't obvious on the first sight, but it is correct.

**Comment by ghost** [comment]
@Rastusik
My update query code will confront the situation that the getTransaction() method returns an object but the isInTransaction variable is false.
This is the conflict that i have seen and it's so weird for me.

**Comment by Rastusik** [comment]
yes I understand, but just run through the code using xdebug and you'll see what I mean ;)
