### ISSUE TITLE
Statement not executed yet

### ISSUE THREAD

**Issue by alouane** [pixelfederation/vitess-php-pdo#15]
Hi,
I got this strange error from src/VitessPdo/PDO/PDOStatement.php => **Statement not executed yet**
I guess $this->cursor always return false

I'm not sure where it comes from, but after a var_dump of the exception object in src/VitessPdo/PDO/QueryExecutor/Result.php

`{\"created\":\"@1488592954.629567158\",\"description\":\"Failed parsing HTTP/2\",\"file\":\"/tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1869,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1488592954.629560308\",\"description\":\"Expected SETTINGS frame as the first frame, got frame type 80\",\"file\":\"/tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/parsing.c\",\"file_line\":280},{\"created\":\"@1488592954.629564476\",\"description\":\"Trying to connect an http1.x server\",\"file\":\"/tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1830,\"http_status\":400}]}"`

Any tip?

**Comment by Rastusik** [comment]
There is something wrong with your vitess setup, this is not a pdo driver bug, this is a grpc error

**Comment by alouane** [comment]
I believe you've experienced a similar problem in [#2131](https://github.com/youtube/vitess/issues/2131), I was facing the same port & hostname issue, somehow only one port worked for me to use vtgate & vtctclient, now I'm using Nodeport service type for both vtgate & vtcld but with no loadbalancing unfortunatly, I think it's an aws load balancer issue, cauze other guys were facing same problem with grpc [#7762](https://github.com/grpc/grpc/issues/7726#issuecomment-240818102)

Thanks
