### ISSUE TITLE
last inserted id always null

### ISSUE THREAD

**Issue by alouane** [pixelfederation/vitess-php-pdo#16]
Hi,
I'm trying to get last insert id of an insert query, but the all $cursor, $lastResult & PDO->lastInsertId() objects have null for that value, is it something related to this driver, or does come from vitess code?
The query is correctly executed by the way

Thanks

**Comment by Rastusik** [comment]
Hi, maybe describe your use case (query and the primary key structure) ... The driver supports lastInsertId() on one column primary keys, as well as vitess should... there is also a unit test for this, which passed during the last version update.

**Comment by alouane** [comment]
Yeah sure, here is my test query:
the table structure contains a primary key: **ID** with auto_increment flag
```php
$sql = "insert into user_credentials set email='$email', password='$password', name='$first_name $last_name', avatar=0, s_avatar='$s_avatar', auth_type='$auth_type', access_level='$access_level', status='$usr_status' ";
$this->container["db"]->exec($sql);
var_dump($this->container["db"]->lastInsertId());

**Comment by Rastusik** [comment]
that's weird because there is a passing test for lastInsertId() here: https://github.com/pixelfederation/vitess-php-pdo/blob/master/tests/VitessPdoTest/PDOTest.php#L187

Could you maybe use Xdebug to step through the code to see, if the value is returned by Vitess client or not? If not, please provide CREATE SQL query for the table and at least one INSERT query with valid data. Thank you.

**Comment by alouane** [comment]
Closing this for now, until I get back to that part of code

Cheers

**Comment by alouane** [comment]
I'm re opening this issue:
The insert id actually does come from vitess client with a null value:
` object(Vitess\Proto\Query\QueryResult)#196 (8) {
          ["fields"]=>
          array(0) {
          }
          ["rows_affected"]=>
          int(1)
          ["insert_id"]=>
          NULL
          ["rows"]=>
          array(0) {
          }
          ["extras"]=>
          NULL
          ["_descriptor":protected]=>
          object(DrSlump\Protobuf\Descriptor)#197 (4) {
            ["class":protected]=>
            string(30) "Vitess\Proto\Query\QueryResult"
            ["name":protected]=>
            string(17) "query.QueryResult"
            ["fields":protected]=>`

As you can see the insert_id attribute is null and does come from **Vitess\Proto\Query\QueryResult**

Also this simple query seems not working neither : `select LAST_INSERT_ID();` when called from php
`vtgate: http://vtgate-test-l621r:15001/: syntax error at position 22 near 'last_insert_id' in /var/www/html/RESTFullAPI2/vendor/vitess/php-client/php/src/Vitess/ProtoUtils.php:56\nStack trace:\n#0 /var/www/html/RESTFullAPI2/vendor/vitess/php-client/php/src/Vitess/VTGateConn.php(53): Vitess\\ProtoUtils::checkError(Object(Vitess\\Proto\\Vtgate\\ExecuteResponse))\n#1 /var/www/html/RESTFullAPI2/vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO/Vitess/Vitess.php(231): Vitess\\VTGateConn->execute(Object(Vitess\\Context), 'select LAST_INS...', Array, 2)\n#2 /var/www/html/RESTFullAPI2/vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO/PDOStatem`

but does actually work when I use cmd: `./kvtctl.sh ExecuteFetchAsDba test-0000000100 "select LAST_INSERTd_ID()"`

Thanks

**Comment by Rastusik** [comment]
@alouane Vitess PHP client is something else than Vitess PHP PDO driver (this repo) ... you need to open an issue in the original vitess repository, where the sources for the Vitess PHP client are present.

Also, the `LAST_INSERT_ID()` query is apparently not supported by Vitess.
