### ISSUE TITLE
Full search issue

### ISSUE THREAD

**Issue by alouane** [pixelfederation/vitess-php-pdo#17]
Hi there
I m testing this search query using match/against:
```sql
select title from video as v where match(v.title, v.tag) against('DEMO' IN BOOLEAN MODE)
``` 

Result:
`"Vitess exception (check previous exception stack): 2: vtgate: http://vtgate-test-l621r:15001/: syntax error at position 45"
`
The same query works well from cmd

Thanks

**Comment by alouane** [comment]
It's actually working if you delete the alias **v.title**:
```sql
select title from video as v where match(title, tag) against('DEMO' IN BOOLEAN MODE)

**Comment by Rastusik** [comment]
Hi, this should be requested in the original Vitess repository - this client is just a PDO wrapper of the original client. But the parsing logic is in the Vitess server side anyway

**Comment by alouane** [comment]
Yep true, issue moved to vitess repo, [#2729](https://github.com/youtube/vitess/issues/2729#issue-218557801)

Thanks
