### ISSUE TITLE
Bind variables are double escaped

### ISSUE THREAD

**Issue by enisoc** [pixelfederation/vitess-php-pdo#2]
Bind variables are being escaped here before sending to the low-level Vitess API:

https://github.com/pixelfederation/vitess-php-pdo/blob/master/src/VitessPdo/PDO/ParamProcessor.php#L111

This results in double-escaped strings, because Vitess already escapes bind variables when it builds the final query just before sending to MySQL. You should be able to just remove the escaping at this level.

**Comment by Rastusik** [comment]
fixed in #v0.1.3
