### ISSUE TITLE
setFetchMode in PDOStatement class

### ISSUE THREAD

**Issue by 0xC0D3D00D** [pixelfederation/vitess-php-pdo#4]
Hi,

We're trying to write a driver for vitess-php-pdo in doctrine DBAL project and it's using PDOStatement::setFetchMode which is absent in vitess-php-pdo API. I need to know what way you suggest to implement this feature?
I'm thinking of keeping a fetch mode variable in PDOStatement class.

**Comment by Rastusik** [comment]
Hi,

yes, I would do it like you say, I suppose. I might look at it this week, if you have some patience. If not I'll gladly merge a pull request :)

**Comment by Rastusik** [comment]
Which fetch mode would you like to have implemented in particular? Because I see some more exotic options there and would prefer to not have to implement every single one of them for now.

**Comment by Rastusik** [comment]
Done

**Comment by 0xC0D3D00D** [comment]
Thank you so much! :+1:
