### ISSUE TITLE
Error when querying

### ISSUE THREAD

**Issue by 0xC0D3D00D** [pixelfederation/vitess-php-pdo#6]
Hi,
I created a new project and added this project as a requirement. but when I try to query something from vitess it always give me the below error:

PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'Vitess\Proto\Vtgate\ExecuteResponse' does not have a method 'deserialize' in vendor/grpc/grpc/src/php/lib/Grpc/AbstractCall.php on line 115
PHP Fatal error:  Uncaught Error: Call to a member function getError() on null in vendor/vitess/php-client/php/src/Vitess/ProtoUtils.php:35
Stack trace:
#0 vendor/vitess/php-client/php/src/Vitess/VTGateConn.php(53): Vitess\ProtoUtils::checkError(NULL)
#1 vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO/Vitess/Vitess.php(207): Vitess\VTGateConn->execute(Object(Vitess\Context), 'select \* from u...', Array, 2)
#2 vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO/PDOStatement.php(152): VitessPdo\PDO\Vitess\Vitess->executeRead(Object(VitessPdo\PDO\QueryAnalyzer\PartiallyParsedQuery), Array)
#3 vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO.php(190): VitessPdo\PDO\PDOStatement->execute()
#4 test2.php(9): VitessPdo\PDO->query('select \* from u...')
#5 {main}

  thrown in vendor/vitess/php-client/php/src/Vitess/ProtoUtils.php on line 35

**Comment by Rastusik** [comment]
@mdhheydari this is a problem in the internal Vitess PHP client, I'll post your issue there - https://github.com/youtube/vitess/issues/1879
