### ISSUE TITLE
Can Not Specify TabletType for Queries

### ISSUE THREAD

**Issue by michaelcurry** [pixelfederation/vitess-php-pdo#7]
We are currently integrating Vitess into our application and have noticed that we are unable to specify TabletType for queries. We do not currently have replicas and need to send all queries to master.  

I see that `ClusterConfig` has a variable `$readFrom` that needs to be changed to allow for read queries to use Master.

Is it in the roadmap to allow for specifying TableType per query  or query type?

Thanks
-- Mike

**Comment by Rastusik** [comment]
@michaelcurry hi, you just need to run this code to direct all read queries to the master tablet:

``` php
$pdo->getCLusterConfig()->readFromMaster();
```

That's it. Feel free to give enhancement suggestions or even better, create a pull request with the implementation. ;)

**Comment by michaelcurry** [comment]
:+1: Thanks,  Did not see that function sitting there.
